In [74]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


#采用kaggle中的数据集来锻炼

#什么是KNN？

- 简单来讲就是寻找离预测值最近的K个点，看下出现频率最高的是哪个分类（分类问题）或者离预测点最近的K个点的值，来预估预测值（比如通过算术平均值等）
- 那么“最近的点”怎么找？ 答案就是通过距离运算，可以采用最简单的欧氏距离，也即sqrt[(x1-x2)^2 +(y1-y2)^2]

#如何通过代码实现？


In [45]:
df = pd.read_excel("C:/Users/guoha/Desktop/PSC.xlsx")

In [46]:
df

Date                                   Place  IMO number  \
0    19.02.2022                 Subic Bay (Philippines)     9731365   
1    19.02.2022  Cagayan de Oro, Mindanao (Philippines)     9702699   
2    19.02.2022              San Fernando (Philippines)     9438810   
3    19.02.2022      South Harbour Manila (Philippines)     9208186   
4    19.02.2022                     Davao (Philippines)     9882372   
..          ...                                     ...         ...   
245  16.02.2022        Vladivostok (Russian Federation)     8808044   
246  16.02.2022                       Takamatsu (Japan)     9115626   
247  16.02.2022                   Nagoya, Aichi (Japan)     9354193   
248  16.02.2022                          Yantai (China)     9343144   
249  16.02.2022                       Mizushima (Japan)     9883821   

          Ship Name Callsign       MMSI                       Flag  \
0          GREAT 61   9V2142  566207000                  Singapore   
1     MARAN HORIZON  9HA4264  249489000                      Malta   
2    UNICORN LOGGER    3ESQ4  370394000                     Panama   
3       WAN HAI 235     BLBP  416337000  Taiwan, Province of China   
4            KOWHAI     HPMX  353369000                     Panama   
..              ...      ...        ...                        ...   
245         WANDA B    5VEA4  671725000                       Togo   
246         MEHRAB1    V3LJ2  312463000                     Belize   
247     APOLLO BENI    3EFD7  353378000                     Panama   
248   FORTUNE LUCKY    V3EF2  312600000                     Belize   
249    AZUL HARMONY   9V6428  563106900                  Singapore   

     Deficiencies Detention Ship Risk Profile at the time of inspection  
0               2        no                                         NaN  
1               0        no                          Standard Risk Ship  
2               0        no                          Standard Risk Ship  
3               0        no                          Standard Risk Ship  
4               0        no                          Standard Risk Ship  
..            ...       ...                                         ...  
245            20        no                                         NaN  
246             2        no                          Standard Risk Ship  
247             1        no                               Low Risk Ship  
248             3        no                              High Risk Ship  
249             0        no                               Low Risk Ship  

[250 rows x 10 columns]

In [47]:
df = df[["Flag","Deficiencies","Ship Risk Profile at the time of inspection"]]

In [48]:
df.rename(columns={"Ship Risk Profile at the time of inspection":"Risk"}, inplace=True)

D:\Devp\DevpTools\Anaconda_2021\lib\site-packages\pandas\core\frame.py:4438: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


In [49]:
df.dropna(axis=0,how="any",inplace=True)

<ipython-input-49-ad77d4e75ba6>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(axis=0,how="any",inplace=True)


In [50]:
df.Risk.unique()

array(['Standard Risk Ship', 'Low Risk Ship', 'High Risk Ship'],
      dtype=object)

In [53]:
df.Flag.unique()


array(['Malta', 'Panama', 'Taiwan, Province of China', 'Marshall Islands',
       'Bahamas', 'Singapore', 'Liberia', 'Hong Kong, China', 'Thailand',
       'Korea, Republic of', 'Cyprus', 'China', 'Cameroon', 'Indonesia',
       'Japan', 'Togo', 'Vietnam', 'Belize', 'Portugal', 'Mongolia',
       'Greece', 'Antigua and Barbuda', 'Isle of Man (GB)', 'Philippines',
       'Sierra Leone', 'Russian Federation', 'Pakistan'], dtype=object)

In [58]:
df = df.replace({'Low Risk Ship':0, 'Standard Risk Ship':1,'High Risk Ship':2 })

In [59]:
df_1 = df[["Deficiencies","Risk"]]

In [60]:
df_1

Deficiencies  Risk
1               0     1
2               0     1
3               0     1
4               0     1
5               0     1
..            ...   ...
243             2     1
246             2     1
247             1     0
248             3     2
249             0     0

[193 rows x 2 columns]

In [61]:
df_2 = pd.get_dummies(df.Flag)

In [62]:
df_2

Antigua and Barbuda  Bahamas  Belize  Cameroon  China  Cyprus  Greece  \
1                      0        0       0         0      0       0       0   
2                      0        0       0         0      0       0       0   
3                      0        0       0         0      0       0       0   
4                      0        0       0         0      0       0       0   
5                      0        0       0         0      0       0       0   
..                   ...      ...     ...       ...    ...     ...     ...   
243                    0        0       1         0      0       0       0   
246                    0        0       1         0      0       0       0   
247                    0        0       0         0      0       0       0   
248                    0        0       1         0      0       0       0   
249                    0        0       0         0      0       0       0   

     Hong Kong, China  Indonesia  Isle of Man (GB)  ...  Panama  Philippines  \
1                   0          0                 0  ...       0            0   
2                   0          0                 0  ...       1            0   
3                   0          0                 0  ...       0            0   
4                   0          0                 0  ...       1            0   
5                   0          0                 0  ...       1            0   
..                ...        ...               ...  ...     ...          ...   
243                 0          0                 0  ...       0            0   
246                 0          0                 0  ...       0            0   
247                 0          0                 0  ...       1            0   
248                 0          0                 0  ...       0            0   
249                 0          0                 0  ...       0            0   

     Portugal  Russian Federation  Sierra Leone  Singapore  \
1           0                   0             0          0   
2           0                   0             0          0   
3           0                   0             0          0   
4           0                   0             0          0   
5           0                   0             0          0   
..        ...                 ...           ...        ...   
243         0                   0             0          0   
246         0                   0             0          0   
247         0                   0             0          0   
248         0                   0             0          0   
249         0                   0             0          1   

     Taiwan, Province of China  Thailand  Togo  Vietnam  
1                            0         0     0        0  
2                            0         0     0        0  
3                            1         0     0        0  
4                            0         0     0        0  
5                            0         0     0        0  
..                         ...       ...   ...      ...  
243                          0         0     0        0  
246                          0         0     0        0  
247                          0         0     0        0  
248                          0         0     0        0  
249                          0         0     0        0  

[193 rows x 27 columns]

In [63]:
raw_result = pd.concat([df_2,df_1],axis=1)

In [64]:
raw_result

Antigua and Barbuda  Bahamas  Belize  Cameroon  China  Cyprus  Greece  \
1                      0        0       0         0      0       0       0   
2                      0        0       0         0      0       0       0   
3                      0        0       0         0      0       0       0   
4                      0        0       0         0      0       0       0   
5                      0        0       0         0      0       0       0   
..                   ...      ...     ...       ...    ...     ...     ...   
243                    0        0       1         0      0       0       0   
246                    0        0       1         0      0       0       0   
247                    0        0       0         0      0       0       0   
248                    0        0       1         0      0       0       0   
249                    0        0       0         0      0       0       0   

     Hong Kong, China  Indonesia  Isle of Man (GB)  ...  Portugal  \
1                   0          0                 0  ...         0   
2                   0          0                 0  ...         0   
3                   0          0                 0  ...         0   
4                   0          0                 0  ...         0   
5                   0          0                 0  ...         0   
..                ...        ...               ...  ...       ...   
243                 0          0                 0  ...         0   
246                 0          0                 0  ...         0   
247                 0          0                 0  ...         0   
248                 0          0                 0  ...         0   
249                 0          0                 0  ...         0   

     Russian Federation  Sierra Leone  Singapore  Taiwan, Province of China  \
1                     0             0          0                          0   
2                     0             0          0                          0   
3                     0             0          0                          1   
4                     0             0          0                          0   
5                     0             0          0                          0   
..                  ...           ...        ...                        ...   
243                   0             0          0                          0   
246                   0             0          0                          0   
247                   0             0          0                          0   
248                   0             0          0                          0   
249                   0             0          1                          0   

     Thailand  Togo  Vietnam  Deficiencies  Risk  
1           0     0        0             0     1  
2           0     0        0             0     1  
3           0     0        0             0     1  
4           0     0        0             0     1  
5           0     0        0             0     1  
..        ...   ...      ...           ...   ...  
243         0     0        0             2     1  
246         0     0        0             2     1  
247         0     0        0             1     0  
248         0     0        0             3     2  
249         0     0        0             0     0  

[193 rows x 29 columns]

In [111]:
raw_data_X = raw_result.drop(["Risk"], axis=1)
raw_data_Y = raw_result.Risk

In [112]:
raw_data_X

Antigua and Barbuda  Bahamas  Belize  Cameroon  China  Cyprus  Greece  \
1                      0        0       0         0      0       0       0   
2                      0        0       0         0      0       0       0   
3                      0        0       0         0      0       0       0   
4                      0        0       0         0      0       0       0   
5                      0        0       0         0      0       0       0   
..                   ...      ...     ...       ...    ...     ...     ...   
243                    0        0       1         0      0       0       0   
246                    0        0       1         0      0       0       0   
247                    0        0       0         0      0       0       0   
248                    0        0       1         0      0       0       0   
249                    0        0       0         0      0       0       0   

     Hong Kong, China  Indonesia  Isle of Man (GB)  ...  Philippines  \
1                   0          0                 0  ...            0   
2                   0          0                 0  ...            0   
3                   0          0                 0  ...            0   
4                   0          0                 0  ...            0   
5                   0          0                 0  ...            0   
..                ...        ...               ...  ...          ...   
243                 0          0                 0  ...            0   
246                 0          0                 0  ...            0   
247                 0          0                 0  ...            0   
248                 0          0                 0  ...            0   
249                 0          0                 0  ...            0   

     Portugal  Russian Federation  Sierra Leone  Singapore  \
1           0                   0             0          0   
2           0                   0             0          0   
3           0                   0             0          0   
4           0                   0             0          0   
5           0                   0             0          0   
..        ...                 ...           ...        ...   
243         0                   0             0          0   
246         0                   0             0          0   
247         0                   0             0          0   
248         0                   0             0          0   
249         0                   0             0          1   

     Taiwan, Province of China  Thailand  Togo  Vietnam  Deficiencies  
1                            0         0     0        0             0  
2                            0         0     0        0             0  
3                            1         0     0        0             0  
4                            0         0     0        0             0  
5                            0         0     0        0             0  
..                         ...       ...   ...      ...           ...  
243                          0         0     0        0             2  
246                          0         0     0        0             2  
247                          0         0     0        0             1  
248                          0         0     0        0             3  
249                          0         0     0        0             0  

[193 rows x 28 columns]

In [113]:
raw_data_Y

1      1
2      1
3      1
4      1
5      1
      ..
243    1
246    1
247    0
248    2
249    0
Name: Risk, Length: 193, dtype: int64

In [114]:
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_Y)

In [115]:
X_train.shape, y_train.shape

((193, 28), (193,))

In [116]:
y_train

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 2, 1, 1, 2, 2, 2, 0, 0, 1,
       2, 1, 1, 2, 0, 1, 1, 1, 2, 1, 2, 1, 0, 2, 2, 0, 0, 2, 0, 1, 1, 0,
       2, 1, 0, 2, 0, 2, 0, 2, 0, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 0, 2, 1, 1, 2, 1, 2, 0,
       2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 0, 0, 0, 2, 0, 0, 2, 0, 2, 0, 1, 1,
       1, 1, 1, 2, 1, 2, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 0, 1, 0, 2, 1,
       1, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2,
       1, 1, 2, 0, 0, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 0], dtype=int64)

In [117]:
#要预测的对象
x = np.array(raw_data_X.iloc[0])

In [153]:
predict_object=np.array(raw_data_X.iloc[:10])

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 4]


In [174]:
from math import sqrt
dist_cum = []
for x in predict_object:
    distances = [sqrt(np.sum(x_train-x)**2) for x_train in X_train]
    dist_cum.append(distances)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 3.0, 4.0, 2.0, 2.0, 1.0, 0.0, 0.0, 1.0, 5.0, 0.0, 1.0, 1.0, 1.0, 2.0, 0.0, 1.0, 0.0, 2.0, 0.0, 0.0, 4.0, 0.0, 0.0, 2.0, 0.0, 5.0, 0.0, 0.0, 5.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 3.0, 2.0, 2.0, 0.0, 3.0, 0.0, 0.0, 2.0, 0.0, 3.0, 1.0, 1.0, 3.0, 0.0, 2.0, 5.0, 0.0, 2.0, 0.0, 5.0, 3.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 1.0, 1.0, 0.0, 0.0, 0.0, 6.0, 2.0, 0.0, 7.0, 0.0, 1.0, 2.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 3.0, 1.0, 5.0, 0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 6.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 10.0, 0.0, 2.0, 7.0, 0.0, 1.0, 0.0, 0.0, 3.0, 0.0, 1.0, 1.0, 0.0, 4.0, 4.0, 0.0, 2.0, 4.0, 7.0, 1.0, 2.0, 12.0, 2.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 5.0, 3.0, 0.0, 0.0, 0.0, 3.0, 4.0, 1.0, 3.0, 0.0, 2.0, 2.0, 1.0, 3.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0

In [197]:
k=20

In [199]:
#order the distances
orders = []
for distance in dist_cum:
    orders.append(np.argsort(distance))

In [200]:
len(orders)

10

In [201]:

prediction_list = []
# we nominated k=10,
for order in orders:
    prediction_list.append([y_train[n] for n in order[:k]])
# result of prediction_list =[1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1]



In [202]:
prediction_list

[[1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [1, 1, 0, 1, 0, 0, 2, 2, 0, 2, 0, 1, 1, 2, 2, 0, 2, 2, 1, 2],
 [1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2],
 [2, 2, 0, 2, 2, 1, 2, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2]]

In [203]:
for num in prediction_list:
    print(Counter(num))

Counter({1: 9, 0: 8, 2: 3})
Counter({1: 9, 0: 8, 2: 3})
Counter({1: 9, 0: 8, 2: 3})
Counter({1: 9, 0: 8, 2: 3})
Counter({1: 9, 0: 8, 2: 3})
Counter({1: 9, 0: 8, 2: 3})
Counter({1: 9, 0: 8, 2: 3})
Counter({2: 8, 1: 6, 0: 6})
Counter({1: 9, 0: 8, 2: 3})
Counter({2: 13, 1: 5, 0: 2})


In [204]:
from collections import Counter
predict_result = []
for num in prediction_list:
    predict_result.append(Counter(num).most_common(1)[0][0])
print(f"The prediction of risk level is {predict_result}")
print("Notes: 0=Low Risk; 1=Standard Risk; 2=High Risk")


The prediction of risk level is [1, 1, 1, 1, 1, 1, 1, 2, 1, 2]
Notes: 0=Low Risk; 1=Standard Risk; 2=High Risk


In [196]:
  y_train[:10]

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 2], dtype=int64)

In [205]:
from sklearn.neighbors import KNeighborsClassifier
KNN_classifier = KNeighborsClassifier(n_neighbors=10)
KNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [206]:
y_predict = KNN_classifier.predict(predict_object)

In [209]:
y_predict

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 2], dtype=int64)

In [211]:
best_score = 0.0
best_k = -1
for k in range(1, 11):
    knn_clf = KNeighborsClassifier(n_neighbors=k)
    knn_clf.fit(X_train, y_train)
    score = knn_clf.score(X_train[:10], y_train[:10])
    if score > best_score:
        best_k = k
        best_score = score
        
print("best_k =", best_k)
print("best_score =", best_score)

best_k = 1
best_score = 0.8
